# Generated by Django 3.1 on 2024-06-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patitasLove', '0002_auto_20240614_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
