# Generated by Django 3.1 on 2024-06-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patitasLove', '0002_auto_20240614_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(max_length=5),
        ),
    ]
