# Generated by Django 4.0.5 on 2024-06-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patitasLove', '0003_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
