# Generated by Django 3.1 on 2024-06-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patitasLove', '0003_auto_20240614_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
